### ISSUE TITLE
Not loading any theme songs

### ISSUE THREAD

**Issue by Zacharybinx34** [LizardByte/Themerr-jellyfin#125]
### Describe the Bug

I have Themer and TMDb installed, and hit download theme songs, but nothing happens and it never plays any when browsing movies. 

Any suggestions? this plugin seems awesome if I could only get it working, thanks!

### Expected Behavior

I am hoping to get it to play theme songs

**Comment by ReenigneArcher** [comment]
I apologize, I did not see this issue until now. I believe this is fixed in nightly, and I am working on getting out a release... and moving to an automated release model so people won't need to wait so long for fixes to come into a "stable" release.

https://github.com/LizardByte/Themerr-jellyfin/pull/144

**Comment by Zacharybinx34** [comment]
> This issue has been fixed and will be available in the next release.

Awesome! Any idea on an ETA?

**Comment by ReenigneArcher** [comment]
If for some reason this is still an issue with the latest release, please open a new issue with enough details to replicate the issue.

**Comment by ReenigneArcher** [comment]
Please give an example movie title.

**Comment by Zacharybinx34** [comment]
Avatar
Dune
Gladiator
Batman Begins
The Dark Knight
The Dark Knight Rises
Frozen
Interstellar
Jurassic Park (entire trilogy)
Inception
The Lord of the Rings (Entire trilogy)
Star Wars (All 3 trilogies)

**Comment by ReenigneArcher** [comment]
Okay. Please provide details about your environment and logs.

**Comment by Zacharybinx34** [comment]
Windows 11. Local storage. 
Log was too big to upload here, so here is a Google drive link to it. 

Thanks!

https://drive.google.com/file/d/1f9czhQQ6-nCx-StEUpmeyiHIwFxwsac5/view?usp=sharing

**Comment by ReenigneArcher** [comment]
Use GitHub gists, or pastebin.

**Comment by Zacharybinx34** [comment]
> Use GitHub gists, or pastebin.

I tried. Said too large/long

**Comment by ReenigneArcher** [comment]
Then provide relevant logs... help me, help you.

**Comment by Zacharybinx34** [comment]
> Then provide relevant logs... help me, help you.

I provided the log that is in my log folder. What other log are you looking for?

**Comment by Zacharybinx34** [comment]
The Hithub Gists finally accepted it. Here it is:
view-source:https://github.com/LizardByte/Themerr-jellyfin/issues/125

**Comment by ReenigneArcher** [comment]
> I provided the log that is in my log folder.

I don't download files from random people.

> The Hithub Gists finally accepted it. Here it is:
view-source:https://github.com/LizardByte/Themerr-jellyfin/issues/125

Please edit. You just linked back to this issue.

**Comment by Zacharybinx34** [comment]
view-source:https://github.com/LizardByte/Themerr-jellyfin/issues/125

**Comment by Zacharybinx34** [comment]
https://gist.githubusercontent.com/Zacharybinx34/ae40b7ba11056afc81eed656b5c389ed/raw/f38537ced5e637ad1ad73a912f0c6af601976124/gistfile1.txt

**Comment by ReenigneArcher** [comment]
> Keeps saying: "theme song not in database, or no internet connection" in the log for all of the movies.

Every time it says this, the movie actually does not exist in our ThemerrDB. This appeared 44 times in your log. I physically checked the first 13 or so, and spot checked the remainder.

You can contribute themes by following the instructions here: https://github.com/LizardByte/ThemerrDB#contributing

> and it never plays any when browsing movies

For this, you will need to enable themes for your client. I don't know how to do that for every client so reach out to the Jellyfin people if you need help with that.

**Comment by Zacharybinx34** [comment]
> > Keeps saying: "theme song not in database, or no internet connection" in the log for all of the movies.
> 
> Every time it says this, the movie actually does not exist in our ThemerrDB. This appeared 44 times in your log. I physically checked the first 13 or so, and spot checked the remainder.
> 
> You can contribute themes by following the instructions here: https://github.com/LizardByte/ThemerrDB#contributing
> 
> > and it never plays any when browsing movies
> 
> For this, you will need to enable themes for your client. I don't know how to do that for every client so reach out to the Jellyfin people if you need help with that.

I did, it plays them for a couple of TV Shows just fine.

**Comment by Zacharybinx34** [comment]
> > Keeps saying: "theme song not in database, or no internet connection" in the log for all of the movies.
> 
> Every time it says this, the movie actually does not exist in our ThemerrDB. This appeared 44 times in your log. I physically checked the first 13 or so, and spot checked the remainder.
> 
> You can contribute themes by following the instructions here: https://github.com/LizardByte/ThemerrDB#contributing
> 
> > and it never plays any when browsing movies
> 
> For this, you will need to enable themes for your client. I don't know how to do that for every client so reach out to the Jellyfin people if you need help with that.

Also, 

> > Keeps saying: "theme song not in database, or no internet connection" in the log for all of the movies.
> 
> Every time it says this, the movie actually does not exist in our ThemerrDB. This appeared 44 times in your log. I physically checked the first 13 or so, and spot checked the remainder.
> 
> You can contribute themes by following the instructions here: https://github.com/LizardByte/ThemerrDB#contributing
> 
> > and it never plays any when browsing movies
> 
> For this, you will need to enable themes for your client. I don't know how to do that for every client so reach out to the Jellyfin people if you need help with that.

Aladdin is in the Database but not working. Seems like it's just not working with movies at all for me for some reason.

**Comment by ReenigneArcher** [comment]
Is this the correct path of the movie?

`[2023-12-08 20:53:40.179 -06:00] [WRN] [18] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path "E:\Media\Videos\Movies\Aladdin\Aladdin.1992.UHD.BluRay.REMUX.2160p.HEVC.TrueHD7.1.Atmos-HDS.mkv"`

**Comment by Zacharybinx34** [comment]
Yeah
