### ISSUE TITLE
Logs full of 404 for missing items

### ISSUE THREAD

**Issue by bonswouar** [LizardByte/Themerr-jellyfin#522]
### Describe the Bug

Not really an issue, it seems to work as expected, but logs are full of 404 Not Found Warnings when trying to request a non-existing item, like:
```
jellyfin  | [17:05:27] [WRN] [25] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: Good Time, contribute:
jellyfin  |   https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Good%20Time%20(2017)&database_url=https://www.themoviedb.org/movie/429200
jellyfin  | System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
jellyfin  |  ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
jellyfin  |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
jellyfin  |    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
jellyfin  |    --- End of inner exception stack trace ---
jellyfin  |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
jellyfin  |    at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)
```

### Expected Behavior

Handle a bit more cleanly the exception, no error log is necessary here I think

### Additional Context

Apparently it was already considered to improve that https://github.com/LizardByte/Themerr-jellyfin/issues/296#issuecomment-2109000053 :)

**Comment by ReenigneArcher** [comment]
This was already addressed in https://github.com/LizardByte/Themerr-jellyfin/pull/331

**Comment by bonswouar** [comment]
Sorry @ReenigneArcher I searched in the issues not in the PRs
Thank you!

**Comment by ReenigneArcher** [comment]
No problem. Unfortunately all our CI builds are hosed right now due to YouTube's anti bot measures... Otherwise I would create a new release.
